### ISSUE TITLE
签名超时 希望能配置一个容错时间

### ISSUE THREAD

**Issue by rxrddd** [wen-gg/webman-api-sign#3]
在实际使用过程中会发现客户端的机器比服务器的机器时间慢1秒钟的情况,会导致请求一直签名超时,是否可以增加一个配置作为容错时间
比如客户端时间比服务端时间慢10s内可以算正常请求

**Comment by wen-gg** [comment]
有超时配置的，你应该没注意 timeout

**Comment by rxrddd** [comment]
> 有超时配置的，你应该没注意 timeout

哦应该是我问题写错的 timeout是客户端时间远小于服务端时间的时候出现的, 但是我现在遇到一种情况是客户端比服务端快的情况 

就会被这句代码判断`wen-gg/webman-api-sign/src/ApiSignService.php  里的 $data[$this->config['fields']['timestamp']] > $ts` 限制直接`签名超时`

**Comment by wen-gg** [comment]
客户端比服务端快你这有问题啊，我上个新版本吧，兼容 + - 时间
